DELIMITER //
USE check
SET GLOBAL event_schedular = ON;
CREATE EVENT delete_when_too_much
	ON SCHEDULE EVERY 1 HOUR STARTS '2019-11-13 15:25'
	DO
	BEGIN IF (SELECT COUNT(*) > 90 FROM log) THEN
		DELETE FROM log ORDER BY date  asc limit 5;
	END IF;
END //
