#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as root or sudo";
  exit 1;
fi

echo -e "Start creating db.$1.arne-vandoorslaer.sb.uclllabs.be.be."
domain=$1
mydate=`date +%Y%m%d`

echo -e "\$TTL 300
@	IN  SOA  ns.$domain.arne-vandoorslaer.sb.uclllabs.be.be. root.$domain.arne-vandoorslaer.sb.uclllabs.be.(
					$mydate"1"	; Serial
					300    		; Refresh
					300  		; Retry
					300 		; Expire
					300 )   	; Negative Cache TTL
;
@		IN	NS	ns.$domain.arne-vandoorslaer.sb.uclllabs.be.
@		IN	NS	ns.arne-vandoorslaer.sb.uclllabs.be.
ns		IN	A	193.191.177.132
@		IN	A	193.191.177.132  " > /etc/bind/zones/db.$domain.arne-vandoorslaer.sb.uclllabs.be


echo "Add zone to named.conf.local."

echo -e "zone \"$domain.arne-vandoorslaer.sb.uclllabs.be\" {
        type master;
        file \"/etc/bind/zones/db.$domain.arne-vandoorslaer.sb.uclllabs.be\";
	notify yes;
};
" >> /etc/bind/named.conf.local 




echo "Add NS record to db.arne-vandoorslaer.sb.uclllabs.be."

echo -e "$domain		IN	NS	ns.arne-vandoorslaer.sb.uclllabs.be." >> /etc/bind/zones/db.arne-vandoorslaer.sb.uclllabs.be

serialline=$(grep "Serial" /etc/bind/zones/db.arne-vandoorslaer.sb.uclllabs.be)
serialnumber=$(echo $serialline | cut -d \; -f 1)
((serialnumber++))
newserial="$serialnumber         ; Serial"
echo $newserial;
sed -i "s/.*Serial.*/\t\t\t     $newserial/g" /etc/bind/zones/db.arne-vandoorslaer.sb.uclllabs.be
echo -e "serial updated, restarting bind9"

systemctl restart bind9

echo "Done."
