#!/bin/bash

if [ "$EUID" -ne 0 ]; then
	echo "Please run as root"
	exit
fi

sub=$(echo $1 | grep -oP ".+(?=(\.arne-vandoorslaer))")

mkdir "/var/www/html/$sub"
mkdir "/var/log/apache2/$1"

echo    "<VirtualHost *:80>
               ServerName $1
               DocumentRoot "/var/www/html/$sub"
               ErrorLog "/var/log/apache2/$1"/error.log
               CustomLog "/var/log/apache2/$1"/access.log combined
       </VirtualHost>" > "/etc/apache2/sites-available/$sub.conf"

echo  "welcome $sub" > "/var/www/html/$sub/index.html"

a2ensite $sub > /dev/null
systemctl reload apache2
