#!/bin/bash

function stop() {
	iptables -F INPUT;
	iptables -F OUTPUT;
	ip6tables -F INPUT;
	ip6tables -F OUTPUT;
}

function start() {
	iptables-restore /etc/network/iptables.rules
	ip6tables-restore /etc/network/ip6tables.rules
}

case $1 in
start)
	start
	;;
stop)
	stop
	;;
restart)
	stop
	start
	;;
*)
	exit 1;
esac
